@hello_xlent_net_HostAddress = http://localhost:5020

GET {{hello_xlent_net_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{hello_xlent_net_HostAddress}}/message/
Accept: application/json
